//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcKutuphane.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DbMvcKutuphaneEntities : DbContext
    {
        public DbMvcKutuphaneEntities()
            : base("name=DbMvcKutuphaneEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TblCezalar> TblCezalars { get; set; }
        public virtual DbSet<TblHareket> TblHarekets { get; set; }
        public virtual DbSet<TblKasa> TblKasas { get; set; }
        public virtual DbSet<TblKategori> TblKategoris { get; set; }
        public virtual DbSet<TblKitap> TblKitaps { get; set; }
        public virtual DbSet<TblPersonel> TblPersonels { get; set; }
        public virtual DbSet<TblUyeler> TblUyelers { get; set; }
        public virtual DbSet<TblYazar> TblYazars { get; set; }
        public virtual DbSet<TblHakkimizda> TblHakkimizdas { get; set; }
        public virtual DbSet<TblIletisim> TblIletisims { get; set; }
        public virtual DbSet<TblMesajlar> TblMesajlars { get; set; }
        public virtual DbSet<TblDuyurular> TblDuyurulars { get; set; }
        public virtual DbSet<TblAdmin> TblAdmins { get; set; }
    
        public virtual ObjectResult<string> EnFazlaKitapYazar()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("EnFazlaKitapYazar");
        }
    }
}
